{% set name = "qcs-sdk-python" %}
{% set version = "0.19.2" %}

package:
  name: qcs-sdk-python-split
  version: {{ version }}

source:
  url: https://github.com/rigetti/qcs-sdk-rust/archive/refs/tags/python/v{{ version }}.tar.gz
  sha256: 825456aa62f4e333a1c62a73c82ab311c7b67e9d32de37ac7a0dd1bc7fde0d7c

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - python
    - toml

outputs:
  - name: qcs-sdk-python
    script: install.sh  # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("qcs-sdk-python", max_pin="x.x") }}
    requirements:
      build:
        # Defines the runtime requirements for the package
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - quil ==0.11.2
        - python
      run_constrained:
        - qcs-sdk-python-grpc-web ==9999999999
    test:
      imports:
        - qcs_sdk.qcs_sdk
      requires:
        - pip
        - rust
      commands:
        - pip check

  - name: qcs-sdk-python-grpc-web
    script: install_grpc.sh  # [unix]
    script: install_grpc.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("qcs-sdk-python-grpc-web", max_pin="x.x") }}
    requirements:
      build:
        # Defines the runtime requirements for the package
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - quil ==0.11.2
        - python
      run_constrained:
        - qcs-sdk-python ==9999999999
    test:
      imports:
        - qcs_sdk.qcs_sdk
      requires:
        - pip
      commands:
        - pip check

  # - Naming conversion
  - name: qcs_sdk_python
    requirements:
      run:
        # - qcs-sdk-python {{ version }}
        - {{ pin_subpackage("qcs-sdk-python", exact=True) }}
    test:
      imports:
        - qcs_sdk.qcs_sdk

  - name: qcs_sdk_python_grpc_web
    requirements:
      run:
        # - qcs-sdk-python-grpc-web {{ version }}
        - {{ pin_subpackage("qcs-sdk-python-grpc-web", exact=True) }}
    test:
      imports:
        - qcs_sdk.qcs_sdk

about:
  home: https://github.com/rigetti/qcs-sdk-rust
  summary: 'Defines the Python bindings to make use of the QCS Rust SDK.'
  description: |
    Defines the Python bindings to make use of the QCS Rust SDK.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://docs.rs/qcs/latest/qcs/

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: qcs-sdk-python
